LinkGrabberDjango/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token
from . import views

urlpatterns = [


    url(r'^backend/account/favourite$', views.FavouriteApiToggle.as_view(), name='favourite'),
    url(r'^backend/account/autoplay$', views.AutoPlayApiToggle.as_view(), name='AutoPlayApiToggle'),
    url(r'^backend/account/autoplaynext', views.AutoPlayNextApiToggle.as_view(), name='AutoPlayNextApiToggle'),
    url(r'^backend/account/fiverecommended', views.FiveRecommended.as_view(), name='FiveRecommendedApiView'),
    url(r'^backend/account/getFavouries', views.getFavouritesAPI.as_view(), name='getFavouritesApiView'),

    url(r'^backend/account/api-token-auth/', obtain_jwt_token),
    url(r'^backend/account/api-token-verify/', verify_jwt_token),

    url(r'^backend/media/GetNextEpisode', views.GetNextEpisodeAPI.as_view(), name='GetNextEpisodeApi'),
    url(r'^backend/media/GetPrevEpisode', views.GetPrevEpisodeAPI.as_view(), name='GetPrevEpisodeApi'),
    url(r'^backend/media/search', views.ApiSearch.as_view(), name='ApiSearch'),
    url(r'^backend/media/getPopular', views.getPopularAPI.as_view(), name='getPopularAPI'),
    url(r'^backend/media/getDetails', views.getDetailsAPI.as_view(), name='getDetails'),
    url(r'^backend/media/getLinks', views.getLinksAPI.as_view(), name='getLinks'),
    url(r'^backend/media/decodeGFile/(?P<file>.*)', views.decodeGFileAPI.as_view(), name='decodeGFile'),


]
urlpatterns = format_suffix_patterns(urlpatterns, allowed=["json","html"])
"""url(r'^$', views.home, name='home'),

url(r'^searchaskforapi/', views.post_list, name='post_list'),
url(r'^search_submit/', views.SearchSubmitView.as_view(), name='search-submit'),
url(r'^search_ajax_submit/', views.SearchAjaxSubmitView.as_view(), name='search-ajax-submit'),

url(r'^post/(?P<id>\d+)/(?P<title>.*)/$', views.post_detail, name='post_detail'),
url(r'^link/', views.links.as_view(), name='links'),
url(r'^play/(?P<showid>.*)/(?P<epid>.*)/(?P<streamid>.*)$', views.play, name='plays'),
url(r'^subtitle.vtt/(?P<title>.*)/(?P<no>\d+)/$', views.subtitle, name='subtitle'),
url(r'^browse/$', views.browseTopList.as_view(), name='toplist'),
url(r'^favourites/$', views.browseFavourites.as_view(), name='favourites'),

url(r'^register/$', views.UserFormView.as_view(), name='register'),
url(r'^login/$', views.UserLoginView.as_view(), name='login'),
url(r'^logout/$', views.UserLogoutView.as_view(), name='logout'),
url(r'^account/$', views.UserProfileView.as_view(), name='profile'),
url(r'^account/autoplay$', views.AutoPlaySwitchRedirect.as_view(), name='AutoPlaySwitch'),"""
"""
    url(r'^send_notification/$', views.send_notification, name='send_notification'),
    url(r'^mark_as_read/$', views.mark_as_read, name='mark_as_read'),
"""

MovieGrabber/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import notifications.urls
from django.views.generic import TemplateView

import LinkGrabberDjango.urls as LinkGrabUrls

urlpatterns = LinkGrabUrls.urlpatterns + [
                  url(r'^admin/', admin.site.urls),
                  url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
                  url(r'^comments/', include('django_comments.urls')),
    url(r'^searchaskforapi/', TemplateView.as_view(template_name="FUCK OFF.html"), name='post_list'),

    url(r'^.*', TemplateView.as_view(template_name="angular_home.html"),name="angular"),

              ]

LinkGrabberDjango/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.models import User

from django.db import models
# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone



class Setting(models.Model):
    Status = models.CharField(max_length=100, default="outdated")
    AppVersion = models.CharField(max_length=100)
    def __unicode__(self):
        return self.Status

class Post(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=200)
    rating = models.FloatField(max_length=10)
    poster = models.URLField()
    year = models.IntegerField()
    def __unicode__(self):
        return self.title

class watched(models.Model):
    user = models.CharField(max_length=100)
    epid = models.CharField(max_length=50)
    epname = models.CharField(max_length=100)
    showid = models.CharField(max_length=50)
    showname = models.CharField(max_length=100)
    date = models.DateTimeField(default=timezone.now, blank=True)
    """class Meta:
        unique_together = ["user", "epid", "showid"]"""
    def __str__(self):
        return self.user + " - " + self.epname

    def __unicode__(self):
        return self.user + " - " + self.epname


    def getdate(self):
        return self.date

class favourite(models.Model):
    user = models.CharField(max_length=100)
    showid = models.CharField(max_length=50)
    showname = models.CharField(max_length=100)
    show = models.BooleanField(default=True)
    newep = models.BooleanField(default=False)
    poster = models.CharField(max_length=300, default="")
    date = models.DateTimeField(default=timezone.now, blank=True)
    count = models.CharField(max_length=10)
    """class Meta:
        unique_together = ["user", "epid", "showid"]"""
    def __str__(self):
        return self.user + " - " + self.showname

    def __unicode__(self):
        return self.user + " - " + self.showname


    def getdate(self):
        return self.date


class FeatureRequest(models.Model):
    user = models.ForeignKey('auth.User')
    title = models.CharField(max_length=100, unique=True)
    body = models.TextField()
    state = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now, blank=True)
    """class Meta:
        unique_together = ["user", "epid", "showid"]"""
    def __str__(self):
        return self.user.username + " - " + self.title

    def __unicode__(self):
        return self.user.username + " - " + self.title

    def getstatus(self):
        if self.state == 0:
            return "Submitted"
        if self.state == 1:
            return "Denied"
        if self.state == 2:
            return "Work in Progress"
        if self.state == 3:
            return "Finished"


    def getdate(self):
        return self.date

class Profile(models.Model):
    user = models.OneToOneField(User, null=False)
    autoplaybest = models.BooleanField(default=False)
    last_activity = models.DateTimeField(default=timezone.now, blank=True)
    night_mode = models.BooleanField(default=False)
    autoplaynext = models.BooleanField(default=False)



@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

LinkGrabberDjango/api/views.py
from rest_framework import generics

from LinkGrabberDjango import apigrabber
from serializers import VideoSerializer
from object import VideoObject

class ViewTest(generics.CreateAPIView):

    serializer_class = VideoSerializer
    permission_classes = []
    authentication_classes = []

LinkGrabberDjango/views.py
from __future__ import print_function

import urllib

from bs4 import BeautifulSoup
import HTMLParser
import json
import re
import unicodedata
import zipfile
from StringIO import StringIO
from collections import Counter

import requests
from digg_paginator import DiggPaginator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views.generic import View
from notifications.signals import notify
from pycaption import CaptionConverter, SRTReader, WebVTTWriter
from rest_framework import authentication, permissions
from rest_framework.response import Response
from rest_framework.views import APIView

from LinkGrabberDjango import apigrabber
from LinkGrabberDjango.api.serializers import SnippetSerializer
from LinkGrabberDjango.forms import User, FeatureRequestForm
from LinkGrabberDjango.templatetags.links_extras import sslimage, urldecode
from .api import subscene
from .forms import UserForm, UserLoginForm
from .models import watched, Profile, favourite, FeatureRequest, Post


def post_list(request):
    pagename = "Search Results"
    return render(request, 'gui/menumain.html', {'posts' : range(40) , "pagename": pagename})


def post_detail(request, id, title):
    seen = False
    isFavourite = False
    seenlist = []

    if request.user.is_authenticated():
        try:
            favourite.objects.get(user=request.user.username,
                                  showid=id, )
            isFavourite = True


            # if we get this far, we have an exact match for this form's data
        except favourite.DoesNotExist:
            # because we didn't get a match
            isFavourite = False

            pass
        seen = watched.objects.filter(user=request.user.username,
                                      showid=id, )
        for key in seen:
            seenlist.append(key.epid)
    jsonseen = json.dumps(seenlist)

    return render(request, 'gui/post_detail.html', {
        "isplay": True,
        "showid": id,
        "seen": seen,
        "jsonseen": jsonseen,
        "isfav": isFavourite,
        "pagename": title
    })


def play(request, epid, streamid, showid):
    data = apigrabber.getstreams(epid)
    showinfo = apigrabber.createdetails(showid)
    otherepisodes = showinfo["posts"]
    index = otherepisodes.index((item for item in otherepisodes if item["id"] == epid).next())

    nextep = False
    prevep = False
    isshow = False
    show = showinfo["title"].encode('utf-8').strip()
    poster = showinfo["poster"]

    if len(otherepisodes) > 3:
        eptitle = otherepisodes[1]['title'].encode('utf-8').strip().replace(u'\xa0', u' ')
        if len(otherepisodes) == index + 1:
            print("first episode")
        else:
            prevep = otherepisodes[index + 1]
        if apigrabber.find_between(eptitle, "S", "E"):
            isshow = True
        if otherepisodes[index - 1]:
            nextep = otherepisodes[index - 1]

    showid = showid
    if isshow:
        pagename = otherepisodes[index]['title'].encode('utf-8').strip()
    else:
        pagename = show

    isplay = True
    post = data[int(streamid)]
    isyt = False
    if post["link"].startswith("GoogleDrive"):
        isyt = True

    return render(request, 'gui/play.html', {'title': id,
                                             "isplay": isplay,
                                             "id": epid,
                                             "poster": poster,
                                             "pagename": pagename,
                                             "isyt": isyt,
                                             "post": post,
                                             "next": nextep, "prev": prevep, "show": show, "showid": showid,
                                             "isshow": isshow})


def subtitle(request, title, no):
    t = re.sub('\(.*?\)', '', title)[:-1]
    film = subscene.search(t, "English")

    zip = requests.get(subscene.zipped_url(film.subtitles[int(no)]))

    fp = StringIO(zip.content)
    archive = zipfile.ZipFile(fp, 'r')
    srt = archive.read(archive.namelist()[0])
    soup = BeautifulSoup(srt)
    # print(soup.originalEncoding)
    converter = CaptionConverter()
    unistring = unicode(srt.decode(soup.originalEncoding))
    if "utf-8" in soup.originalEncoding:
        unistring = unistring[1:]
    converter.read(unistring, SRTReader())
    html_parser = HTMLParser.HTMLParser()

    return HttpResponse(html_parser.unescape(converter.write(WebVTTWriter()).encode('ascii', 'ignore')),
                        content_type="text/vtt")


def home(request):
    favourites = favourite.objects.filter(user=request.user.username, ).order_by("date").reverse()[:10]
    return render(request, 'gui/home.html',
                  {"pagename": "Home", "favourites": favourites})


class browseTopList(View):
    def get(self, request):
        type = request.GET.get('cat')
        page = request.GET.get('page', 1)
        sort = request.GET.get('sort', "popular")
        toplist = apigrabber.getToplist(type, page, sort)
        # print(len(toplist))
        paginator = DiggPaginator(toplist, 24, body=6)
        try:
            movies = DiggPaginator.page(paginator, number=page)
        except PageNotAnInteger:
            movies = DiggPaginator.page(paginator, number=1)
        except EmptyPage:
            movies = DiggPaginator.page(paginator, number=DiggPaginator.num_pages)

        return render(request, 'gui/toplist.html',
                      {"posts": movies, "type": type, "page": int(page), "pagename": "Browse Top List"})


class browseFavourites(View):
    def get(self, request):
        page = request.GET.get('page', 1)
        favourites_list = favourite.objects.filter(user=request.user.username, ).order_by("date").reverse()
        paginator = Paginator(favourites_list, 10)
        try:
            favourites = paginator.page(page)
        except PageNotAnInteger:
            favourites = paginator.page(1)
        except EmptyPage:
            favourites = paginator.page(paginator.num_pages)
        return render(request, 'gui/favourites.html',
                      {"posts": favourites, "page": int(page), "pagename": "Browse Top List"})


class links(View):
    def post(self, request):
        show = unicodedata.normalize("NFKD", request.POST.get("foo").replace(u'\xa0', u' '))
        epid = request.POST.get("epid")
        epname = unicodedata.normalize("NFKD", request.POST.get("epname").replace(u'\xa0', u' '))
        showid = request.POST.get("showid")
        links = apigrabber.getstreams(epid)

        if request.user.is_authenticated():
            user = User.objects.get(pk=request.user.id)
            w = watched(user=request.user.username, epid=epid, epname=epname.encode('utf-8').strip(), showid=showid,
                        showname=show.encode('utf-8').strip())

            try:
                watched.objects.get(user=request.user.username,
                                    epid=epid,
                                    epname=epname.encode('utf-8').strip(),
                                    showid=showid,
                                    showname=show.encode('utf-8').strip())

                # if we get this far, we have an exact match for this form's data
            except watched.DoesNotExist:
                # because we didn't get a match
                w.save()
                pass
            if user.profile.autoplaybest:
                bestq = None
                for link in links:
                    if not bestq:
                        quality = apigrabber.find_between(link["name"], "Video ", " (")

                        if quality.encode('utf-8') == "1080p":
                            bestq = link["type"]
                        elif quality.encode('utf-8') == "720p":
                            bestq = link["type"]
                        elif quality.encode('utf-8') == "480p":
                            bestq = link["type"]
                        elif quality.encode('utf-8') == "360p":
                            bestq = link["type"]
                        elif link["name"].startswith("Google Direct"):
                            bestq = link["type"]

                return redirect('plays', showid=showid, epid=epid, streamid=bestq)
        return render(request, 'gui/links.html', {'posts': links, "pagename": epname, "showid": showid})


class SearchSubmitView(View):
    template = 'gui/search_submit.html'
    response_message = 'This is the response'

    def post(self, request):
        template = loader.get_template(self.template)
        query = request.POST.get('search', '')

        # A simple query for Item objects whose title contain 'query'
        items = apigrabber.createmainlisting(query)

        context = {'title': self.response_message, 'query': query, 'items': items}

        rendered_template = template.render(context, request)
        return HttpResponse(rendered_template, content_type='text/html')


class SearchAjaxSubmitView(SearchSubmitView):
    template = 'gui/search_results.html'
    response_message = 'This is the AJAX response'


class UserFormView(View):
    title = "Register"
    form_class = UserForm
    template_name = "gui/user/form.html"

    # blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {"form": form, "title": self.title})

    # submit
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data["username"]

LinkGrabberDjango/templates/gui/user/form.html
{% extends 'gui/base.html' %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <h1>{{ title }}</h1>
                <hr/>
                <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-default" value="{{ title }}">

                </form>

            </div>
        </div>
    </div>

{% endblock %}

LinkGrabberDjango/templates/gui/user/profile.html
{% extends 'gui/base.html' %}
{% load staticfiles %}
{% load links_extras %}
{% load comments %}
{% load crispy_forms_tags %}
{% load analytical %}
{% load notifications_tags %}

{% block extra_headers %}
    <link href="{% static "css/profile.css" %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
        <script>
        $(document).ready(function() {
            $("#send-notification-button").popover({
                container: "body",
                html: true,
                placement: "right",
                content: function() {
                    return $("#send-notification-popover").html();
                },
                trigger: "click"
            });
        });
    </script>


    <div class="container">
        <div class="row">
            <div class="user-dashboard">
                <h1>Settings: {{ settings.username }}</h1>
                <hr/>
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12 gutter">

                        <div class="sales">
                            <h2> Auto-Select Best Quality Link: </h2>

                            <div class="btn-group">

                                <!-- Rounded switch -->
                                <label class="switch">
                                    <input type="checkbox" id="checkboxautoplay">
                                    <div class="slider round">

                                    </div>
                                </label>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 gutter">

                        <div class="sales">
                            <h2> NightMode(BETA): </h2>

                            <div class="btn-group">

                                <!-- Rounded switch -->
                                <label class="switch">
                                    <input type="checkbox" id="checkboxNightMode">
                                    <div class="slider round">

                                    </div>
                                </label>

                            </div>
                        </div>

                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 gutter">

                        <div class="sales">
                            <h2> AutoPlayNext(BETA): </h2>

                            <div class="btn-group">

                                <!-- Rounded switch -->
                                <label class="switch">
                                    <input type="checkbox" id="checkboxAutoNext">
                                    <div class="slider round">

                                    </div>
                                </label>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="user-dashboard">
                <h1>Feature Request</h1>
                <hr>

                <div class="row">
                    <div class="col-md-10 col-sm-12 col-xs-12 gutter col-md-offset-1">
                        <ul class="list-group">
                            <div class="panel-group">
                                {% for feature in requests %}
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <a data-toggle="collapse" href="#collapse{{ feature.pk }}">
                                                {{ feature.title }}
                                                <span class="badge pull-right">{{ feature.state|status }}</span>


                                                {% if user.is_superuser %}
                                                    <span class="label label-info pull-right"
                                                          style="margin-right: 5px;">{{ feature.user.username }}</span>
                                                {% endif %}
                                            </a>
                                        </div>
                                        <div class="panel-body">
                                            <div id="collapse{{ feature.pk }}" class="panel-collapse collapse">
                                                <span>{{ feature.body }}</span>
                                                <hr>
                                                {% get_comment_count for feature as comment_count %}
                                                {% render_comment_list for feature %}
                                                {% get_comment_form for feature as form %}
                                                <form action="{% comment_form_target %}" method="post">
                                                    <div class="form-group">
                                                        <input type="hidden" name="next" value="{{ request.path }}"/>
                                                        {% csrf_token %}
                                                        {% for field in form %}
                                                            {% ifequal field.name "name" %}
                                                                <input id="id_name" type="hidden" name="name"
                                                                       value="{{ user.username }}"/>
                                                            {% else %}
                                                                {% ifequal field.name "email" %}
                                                                    <input type="hidden" name="email"
                                                                           value="noboy@nobody.com"
                                                                           id="id_email"/>
                                                                {% else %}
                                                                    {% ifequal field.name "url" %}
                                                                        <p style="display:none;">
                                                                            <label for="id_url">URL:</label>
                                                                            <input name="url" id="id_url" type="url">
                                                                        </p>
                                                                    {% else %}
                                                                        {% ifequal field.name "honeypot" %}
                                                                            <p style="display:none;">
                                                                                <label for="id_honeypot">If you enter
                                                                                    anything
                                                                                    in this
                                                                                    field
                                                                                    your comment will be treated as
                                                                                    spam:</label> <input
                                                                                    name="honeypot" id="id_honeypot"
                                                                                    type="text">
                                                                            </p>
                                                                        {% else %}
                                                                            {% ifequal field.name "comment" %}
                                                                                <label for="comment">Comment:</label>
                                                                                <textarea class="form-control" rows="5"
                                                                                          name="comment" id="id_comment"
                                                                                          required=""

                                                                                          maxlength="3000"></textarea>
                                                                            {% else %}

                                                                                {{ field }}
                                                                            {% endifequal %}
                                                                        {% endifequal %}
                                                                    {% endifequal %}
                                                                {% endifequal %}
                                                            {% endifequal %}
                                                        {% endfor %}
                                                        <input class="btn btn-default" type="submit" name="submit"
                                                               value="Post">
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </ul>
                    </div>

                    <div class="col-md-10 col-sm-12 col-xs-12 gutter col-md-offset-1">

                        <div class="">

                            <form role="form" action="" method="post">
                                {% csrf_token %}
                                <div class="form-group">


                                    <label for="id_title">Title:</label>
                                    <input type="text" name="title" required id="id_title" maxlength="100"
                                           class="form-control"
                                           placeholder="Title">


                                    <label for="id_body">Description:</label>
                                    <textarea name="body" id="id_body" class="form-control" rows="3" required
                                              placeholder="Describe your idea"></textarea>
                                    <span>Please note: We can't change the contents of the site, this is only a web interface for the Movie HD app.</span>
                                    <br>
                                    <button class="btn btn-success" type="submit">Submit</button>

                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>


    </div>
    </div>

{% endblock %}
<script>
    {% block jquery %}
        $("#checkboxautoplay").prop("checked", {{ settings.profile.autoplaybest|lower }});
        $("#checkboxautonext").prop("checked", {{ settings.profile.autoplaynext|lower }});

        $("#checkboxNightMode").prop("checked", {{ settings.profile.night_mode|lower }});
        $(document).ready(function () {
            $("input#checkboxautoplay").click(function (e) {
                e.preventDefault();
                e.stopPropagation();
                var thiselement = this;
                $.ajax({
                    url: '/api/account/autoplay',
                    dataType: 'json',
                    success: function (data) {
                        $(thiselement).prop("checked", data.autoplay);
                    }

                });
            })
            $("input#checkboxNightMode").click(function (e) {
                e.preventDefault();
                e.stopPropagation();
                var thiselement = this;
                $.ajax({
                    url: '/api/account/nightmode',
                    dataType: 'json',
                    success: function (data) {
                        $(thiselement).prop("checked", data.nightmode);
                    }

                });
            })
            $("input#checkboxAutoNext").click(function (e) {
                e.preventDefault();
                e.stopPropagation();
                var thiselement = this;
                $.ajax({
                    url: '/api/account/autoplaynext',
                    dataType: 'json',
                    success: function (data) {
                        $(thiselement).prop("checked", data.autoplaynext);
                    }

                });
            })
        });

    {% endblock %}
</script>